Feature/backend structure
forssea-robotics/hmi-angular-ssr-front-end-dev-hiring pull request #4
Opened 2023-12-12 09:09 UTC by Mathilde-Frere

1- Configure server to fit with websocket usage.

2-Add back-end API about:
- Thruster
- Radio

3-Fix some minor bug on HMI part

2023-12-12 17:13 UTC, PierreSachot requested changes
Really good job, thanks a lot! Really nice the random behavior and everything! 

Hope we will find the person we need!

2023-12-12 17:13 UTC, PierreSachot commented on src/backend/services/api-radio.service.ts
> +    if(radioState.powerOn !== instance._fakeRadioData.powerOn) {
Here you can only update 1 value at a time. If you change the power status and frequency, only power status is updated. 

Keep it like this, if the futur employe correct this we would know that he is the one ahah

2023-12-12 17:13 UTC, PierreSachot commented on src/backend/services/api-thruster.service.ts
> +    return res.status(StatusCode.SuccessOK).send({ thrusterListState });
Same as before, I would do a JSON.stringify(thrusterListState)

2023-12-12 17:13 UTC, PierreSachot commented on src/frontend/app/components/thruster-list-container/thruster-list-container.component.html
> +  <div>
Ahah, Too much help ? :p

2023-12-13 10:56 UTC, Mathilde-Frere commented on src/backend/services/api-radio.service.ts
> +    return res.status(StatusCode.SuccessOK).send({ radioState });
It has been chosen to return : `return res.status(StatusCode.SuccessOK).send(radioState);`

2023-12-13 10:57 UTC, Mathilde-Frere commented on src/backend/services/api-thruster.service.ts
> +    return res.status(StatusCode.SuccessOK).send({ thrusterListState });
It has been chosen to return : `return res.status(StatusCode.SuccessOK).send(thrusterListState);`

2023-12-13 12:10 UTC, PierreSachot approved these changes
Good job! Thanks a lot for your hard work!

We are ready to hire!

2023-12-13 12:10 UTC, PierreSachot commented on README.md
> +- Data must be updated in real time across multiple open browser windows (websocket network protocol).
Great!

2023-12-13 12:23 UTC, merged